"""add_default_gst_rate

Revision ID: 1c8ec1764fc1
Revises: 20230626_1540_cleanup_schema
Create Date: 2026-06-27 01:47:34.510893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8ec1764fc1'
down_revision: Union[str, None] = '20230626_1540_cleanup_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('default_gst_rate', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('credit_note_items', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_credit_note_items_batch_id'), 'credit_note_items', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'credit_note_items', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.add_column('debit_note_items', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_debit_note_items_batch_id'), 'debit_note_items', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'debit_note_items', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_invoice_items_batch_id'), 'invoice_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_purchase_bill_items_batch_id'), 'purchase_bill_items', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'purchase_bill_items', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_stock_entries_batch_id'), 'stock_entries', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_entries_batch_id'), table_name='stock_entries')
    op.drop_constraint(None, 'purchase_bill_items', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_bill_items_batch_id'), table_name='purchase_bill_items')
    op.drop_index(op.f('ix_invoice_items_batch_id'), table_name='invoice_items')
    op.drop_constraint(None, 'debit_note_items', type_='foreignkey')
    op.drop_index(op.f('ix_debit_note_items_batch_id'), table_name='debit_note_items')
    op.drop_column('debit_note_items', 'batch_id')
    op.drop_constraint(None, 'credit_note_items', type_='foreignkey')
    op.drop_index(op.f('ix_credit_note_items_batch_id'), table_name='credit_note_items')
    op.drop_column('credit_note_items', 'batch_id')
    op.drop_column('companies', 'default_gst_rate')
    # ### end Alembic commands ###
