"""check schema drift

Revision ID: 28ad1d181fc3
Revises: a448bea5d7b2
Create Date: 2026-05-16 19:04:21.842972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28ad1d181fc3'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_statement_line_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('stock_entries_batch_id_fkey', 'stock_entries', type_='foreignkey')
    op.drop_table('system_settings')
    op.drop_index('idx_bank_statement_lines_is_matched', table_name='bank_statement_lines')
    op.drop_index('ix_bank_statement_lines_statement_id', table_name='bank_statement_lines')
    op.drop_table('bank_statement_lines')
    op.drop_index('ix_purchase_bill_items_product_id', table_name='purchase_bill_items')
    op.drop_index('ix_purchase_bill_items_purchase_bill_id', table_name='purchase_bill_items')
    op.drop_table('purchase_bill_items')
    op.drop_index('ix_gst_cache_gstin', table_name='gst_cache')
    op.drop_table('gst_cache')
    op.drop_table('company_settings')
    op.drop_index('ix_batches_batch_number', table_name='batches')
    op.drop_index('ix_batches_company_id', table_name='batches')
    op.drop_index('ix_batches_expiry_date', table_name='batches')
    op.drop_index('ix_batches_product_id', table_name='batches')
    op.drop_table('batches')
    op.drop_index('idx_bank_statements_account_id', table_name='bank_statements')
    op.drop_index('ix_bank_statements_company_id', table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_table('security_audits')
    op.alter_column('companies', 'tan_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('companies', 'is_tds_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('companies', 'is_tcs_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('companies', 'is_gst_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('companies', 'bank_branch',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('companies', 'account_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('companies', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_companies_current_fy_id'), 'companies', ['current_fy_id'], unique=False)
    op.drop_column('companies', 'state_code')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'industry_type')
    op.drop_column('companies', 'business_type')
    op.drop_column('companies', 'group_code')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'work_type')
    op.drop_column('companies', 'default_tax_rate')
    op.drop_column('companies', 'bank_details')
    op.drop_column('companies', 'company_code')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'trade_nature')
    op.alter_column('credit_note_items', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.drop_index('ix_credit_note_items_product_id', table_name='credit_note_items')
    op.alter_column('credit_notes', 'note_date',
               existing_type=sa.DATE(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('credit_notes', 'reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('credit_notes', 'gst_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index('ix_credit_notes_status', table_name='credit_notes')
    op.drop_column('credit_notes', 'notes')
    op.alter_column('customers', 'gst_treatment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('customers', 'msme_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('customers', 'type_of_trader',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('customers', 'state_code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('customers', 'distance_km',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('customers', 'discount_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('customers', 'tds_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('customers', 'sub_ledger',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('customers', 'broker_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('customers', 'opening_balance_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('customers', 'bill_by_bill',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('customers', 'gst_filling_method',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('customers', 'check_credit_days',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('customers', 'type_of_supply',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('customers', 'consider_supply_type',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('customers', 'aadhaar_card_number')
    op.drop_column('customers', 'ledger_name')
    op.drop_column('customers', 'address3')
    op.drop_column('customers', 'bill_by_bill_adjustment')
    op.drop_column('customers', 'gst_applicable')
    op.drop_column('customers', 'phone_no_3')
    op.drop_column('customers', 'checking_credit_days_during_bill_entry')
    op.drop_column('customers', 'debit_credit')
    op.alter_column('debit_note_items', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.drop_index('ix_debit_note_items_product_id', table_name='debit_note_items')
    op.alter_column('debit_notes', 'note_date',
               existing_type=sa.DATE(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('debit_notes', 'reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('debit_notes', 'gst_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_index('ix_debit_notes_status', table_name='debit_notes')
    op.drop_column('debit_notes', 'notes')
    op.alter_column('document_sequences', 'prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('document_sequences', 'suffix',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('uq_company_doc_type', 'document_sequences', type_='unique')
    op.create_unique_constraint('uq_document_sequences_type', 'document_sequences', ['company_id', 'document_type'])
    op.alter_column('fiscal_years', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_unique_constraint('uq_fiscal_years_label', 'fiscal_years', ['company_id', 'label'])
    op.alter_column('invoice_items', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'discount_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'hsn_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index('ix_invoice_items_product_id', table_name='invoice_items')
    op.alter_column('invoices', 'gst_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('invoices', 'gst_transaction_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('invoices', 'gst_method',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('invoices', 'broker_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'shipping_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'vehicle_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('invoices', 'transporter_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'eway_bill_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('invoices', 'eway_bill_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('invoices', 'ack_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_invoices_created_at', table_name='invoices')
    op.drop_index('idx_invoices_status', table_name='invoices')
    op.drop_index('idx_invoices_status_date', table_name='invoices')
    op.drop_index('ix_invoices_eway_bill_no', table_name='invoices')
    op.drop_index('ix_invoices_irn', table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.alter_column('journal_entries', 'entry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index('idx_payments_party_id', table_name='payments')
    op.drop_index('idx_payments_ref_id', table_name='payments')
    op.drop_index('ix_payments_is_reconciled', table_name='payments')
    op.drop_column('payments', 'reconciled_at')
    op.drop_column('payments', 'cleared_date')
    op.drop_column('payments', 'statement_line_id')
    op.drop_index('idx_products_name_trgm', table_name='products', postgresql_using='gin')
    op.drop_index('ix_products_barcode', table_name='products')
    op.drop_index('idx_purchase_bills_status_date', table_name='purchase_bills')
    op.create_index(op.f('ix_purchase_bills_bill_date'), 'purchase_bills', ['bill_date'], unique=False)
    op.drop_column('purchase_bills', 'sgst_amount')
    op.drop_column('purchase_bills', 'gst_type')
    op.drop_column('purchase_bills', 'round_off_amount')
    op.drop_column('purchase_bills', 'place_of_supply')
    op.drop_column('purchase_bills', 'igst_amount')
    op.drop_column('purchase_bills', 'cgst_amount')
    op.add_column('purchase_order_items', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('purchase_order_items', sa.Column('product_sku', sa.String(length=100), nullable=True))
    op.drop_column('purchase_order_items', 'hsn_code')
    op.drop_column('purchase_orders', 'sgst_amount')
    op.drop_column('purchase_orders', 'igst_amount')
    op.drop_column('purchase_orders', 'cgst_amount')
    op.add_column('sales_order_items', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('sales_order_items', sa.Column('product_sku', sa.String(length=100), nullable=True))
    op.drop_column('sales_order_items', 'hsn_code')
    op.add_column('sales_orders', sa.Column('gst_type', sa.String(length=30), nullable=False))
    op.alter_column('sales_orders', 'gst_transaction_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sales_orders', 'gst_method',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('sales_orders', 'broker_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('sales_orders', 'shipping_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_sales_orders_status_date', table_name='sales_orders')
    op.drop_index('idx_stock_entries_product_date', table_name='stock_entries')
    op.drop_index('ix_stock_entries_batch_id', table_name='stock_entries')
    op.drop_column('stock_entries', 'batch_id')
    op.alter_column('suppliers', 'gst_treatment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('suppliers', 'msme_no',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('suppliers', 'type_of_trader',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('suppliers', 'state_code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('suppliers', 'distance_km',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'discount_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'tds_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'sub_ledger',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('suppliers', 'broker_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('suppliers', 'opening_balance_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('suppliers', 'bill_by_bill',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('suppliers', 'gst_filling_method',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('suppliers', 'check_credit_days',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('suppliers', 'type_of_supply',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('suppliers', 'consider_supply_type',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('suppliers', 'aadhaar_card_number')
    op.drop_column('suppliers', 'ledger_name')
    op.drop_column('suppliers', 'address3')
    op.drop_column('suppliers', 'bill_by_bill_adjustment')
    op.drop_column('suppliers', 'gst_applicable')
    op.drop_column('suppliers', 'phone_no_3')
    op.drop_column('suppliers', 'checking_credit_days_during_bill_entry')
    op.drop_column('suppliers', 'debit_credit')
    op.drop_index('ix_user_sessions_refresh_token', table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.drop_column('user_sessions', 'updated_at')
    op.alter_column('users', 'pin_login_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'failed_pin_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.drop_column('users', 'pin_length')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_length', sa.INTEGER(), server_default=sa.text('4'), autoincrement=False, nullable=True))
    op.alter_column('users', 'failed_pin_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('users', 'pin_login_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('user_sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.create_index('ix_user_sessions_refresh_token', 'user_sessions', ['refresh_token'], unique=True)
    op.add_column('suppliers', sa.Column('debit_credit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('checking_credit_days_during_bill_entry', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('phone_no_3', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('gst_applicable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('bill_by_bill_adjustment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('address3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('ledger_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('aadhaar_card_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('suppliers', 'consider_supply_type',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('suppliers', 'type_of_supply',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('suppliers', 'check_credit_days',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('suppliers', 'gst_filling_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('suppliers', 'bill_by_bill',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('suppliers', 'opening_balance_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('suppliers', 'broker_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('suppliers', 'sub_ledger',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('suppliers', 'tds_rate',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'discount_pct',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'distance_km',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('suppliers', 'state_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('suppliers', 'type_of_trader',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('suppliers', 'msme_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('suppliers', 'gst_treatment',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('stock_entries', sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('stock_entries_batch_id_fkey', 'stock_entries', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_stock_entries_batch_id', 'stock_entries', ['batch_id'], unique=False)
    op.create_index('idx_stock_entries_product_date', 'stock_entries', ['product_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_sales_orders_status_date', 'sales_orders', ['status', sa.text('order_date DESC')], unique=False)
    op.alter_column('sales_orders', 'shipping_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('sales_orders', 'broker_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('sales_orders', 'gst_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('sales_orders', 'gst_transaction_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('sales_orders', 'gst_type')
    op.add_column('sales_order_items', sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('sales_order_items', 'product_sku')
    op.drop_column('sales_order_items', 'product_name')
    op.add_column('purchase_orders', sa.Column('cgst_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('igst_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_orders', sa.Column('sgst_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_order_items', sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('purchase_order_items', 'product_sku')
    op.drop_column('purchase_order_items', 'product_name')
    op.add_column('purchase_bills', sa.Column('cgst_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_bills', sa.Column('igst_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_bills', sa.Column('place_of_supply', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('purchase_bills', sa.Column('round_off_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.add_column('purchase_bills', sa.Column('gst_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('purchase_bills', sa.Column('sgst_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_purchase_bills_bill_date'), table_name='purchase_bills')
    op.create_index('idx_purchase_bills_status_date', 'purchase_bills', ['status', sa.text('bill_date DESC')], unique=False)
    op.create_index('ix_products_barcode', 'products', ['barcode'], unique=False)
    op.create_index('idx_products_name_trgm', 'products', ['name'], unique=False, postgresql_using='gin')
    op.add_column('payments', sa.Column('statement_line_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('cleared_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('reconciled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('payments_statement_line_id_fkey', 'payments', 'bank_statement_lines', ['statement_line_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_payments_is_reconciled', 'payments', ['is_reconciled'], unique=False)
    op.create_index('idx_payments_ref_id', 'payments', ['reference_id'], unique=False)
    op.create_index('idx_payments_party_id', 'payments', ['party_id'], unique=False)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('journal_entries', 'entry_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.create_index('ix_invoices_irn', 'invoices', ['irn'], unique=False)
    op.create_index('ix_invoices_eway_bill_no', 'invoices', ['eway_bill_no'], unique=False)
    op.create_index('idx_invoices_status_date', 'invoices', ['status', sa.text('invoice_date DESC')], unique=False)
    op.create_index('idx_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoices_created_at', 'invoices', [sa.text('created_at DESC')], unique=False)
    op.alter_column('invoices', 'ack_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('invoices', 'eway_bill_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('invoices', 'eway_bill_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('invoices', 'transporter_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'vehicle_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('invoices', 'shipping_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'broker_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('invoices', 'gst_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'gst_transaction_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'gst_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index('ix_invoice_items_product_id', 'invoice_items', ['product_id'], unique=False)
    op.alter_column('invoice_items', 'hsn_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('invoice_items', 'discount_pct',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_items', 'tax_rate',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_constraint('uq_fiscal_years_label', 'fiscal_years', type_='unique')
    op.alter_column('fiscal_years', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint('uq_document_sequences_type', 'document_sequences', type_='unique')
    op.create_unique_constraint('uq_company_doc_type', 'document_sequences', ['company_id', 'document_type'])
    op.alter_column('document_sequences', 'suffix',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('document_sequences', 'prefix',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('debit_notes', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_debit_notes_status', 'debit_notes', ['status'], unique=False)
    op.alter_column('debit_notes', 'gst_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('debit_notes', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('debit_notes', 'note_date',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_DATE'),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_index('ix_debit_note_items_product_id', 'debit_note_items', ['product_id'], unique=False)
    op.alter_column('debit_note_items', 'tax_rate',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.add_column('customers', sa.Column('debit_credit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('checking_credit_days_during_bill_entry', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('phone_no_3', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('gst_applicable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('bill_by_bill_adjustment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('address3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('ledger_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('aadhaar_card_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('customers', 'consider_supply_type',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customers', 'type_of_supply',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('customers', 'check_credit_days',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('customers', 'gst_filling_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('customers', 'bill_by_bill',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('customers', 'opening_balance_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('customers', 'broker_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('customers', 'sub_ledger',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('customers', 'tds_rate',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('customers', 'discount_pct',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('customers', 'distance_km',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('customers', 'state_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('customers', 'type_of_trader',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('customers', 'msme_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('customers', 'gst_treatment',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('credit_notes', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_credit_notes_status', 'credit_notes', ['status'], unique=False)
    op.alter_column('credit_notes', 'gst_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('credit_notes', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('credit_notes', 'note_date',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_DATE'),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_index('ix_credit_note_items_product_id', 'credit_note_items', ['product_id'], unique=False)
    op.alter_column('credit_note_items', 'tax_rate',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.add_column('companies', sa.Column('trade_nature', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('company_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('bank_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('default_tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('work_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('group_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('industry_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('state_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_current_fy_id'), table_name='companies')
    op.alter_column('companies', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('companies', 'account_no',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('companies', 'bank_branch',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('companies', 'is_gst_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('companies', 'is_tcs_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('companies', 'is_tds_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('companies', 'tan_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_table('security_audits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_run_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('machine_hwid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='security_audits_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='security_audits_pkey')
    )
    op.create_table('bank_statements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('import_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='bank_statements_account_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='bank_statements_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='bank_statements_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_bank_statements_company_id', 'bank_statements', ['company_id'], unique=False)
    op.create_index('idx_bank_statements_account_id', 'bank_statements', ['account_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('manufacturing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cost_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='batches_company_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='batches_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='batches_pkey'),
    sa.UniqueConstraint('company_id', 'product_id', 'batch_number', name='uq_batches_product_batch')
    )
    op.create_index('ix_batches_product_id', 'batches', ['product_id'], unique=False)
    op.create_index('ix_batches_expiry_date', 'batches', ['expiry_date'], unique=False)
    op.create_index('ix_batches_company_id', 'batches', ['company_id'], unique=False)
    op.create_index('ix_batches_batch_number', 'batches', ['batch_number'], unique=False)
    op.create_table('company_settings',
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_eway_bill_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_einvoicing_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('turnover_exceeds_5cr', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_whatsapp_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('whatsapp_api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_gmail_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ca_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gmail_app_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_barcode_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('barcode_auto_generate', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auto_reset_sequences', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='company_settings_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', name='company_settings_pkey')
    )
    op.create_table('gst_cache',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gstin', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('legal_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trade_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('constitution', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('taxpayer_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nature_of_business', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gst_cache_pkey')
    )
    op.create_index('ix_gst_cache_gstin', 'gst_cache', ['gstin'], unique=True)
    op.create_table('purchase_bill_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('purchase_bill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('discount_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('hsn_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='purchase_bill_items_product_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bills.id'], name='purchase_bill_items_purchase_bill_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='purchase_bill_items_pkey')
    )
    op.create_index('ix_purchase_bill_items_purchase_bill_id', 'purchase_bill_items', ['purchase_bill_id'], unique=False)
    op.create_index('ix_purchase_bill_items_product_id', 'purchase_bill_items', ['product_id'], unique=False)
    op.create_table('bank_statement_lines',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('statement_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('withdrawal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('deposit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_matched', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], name='bank_statement_lines_statement_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='bank_statement_lines_pkey')
    )
    op.create_index('ix_bank_statement_lines_statement_id', 'bank_statement_lines', ['statement_id'], unique=False)
    op.create_index('idx_bank_statement_lines_is_matched', 'bank_statement_lines', ['is_matched'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('license_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_activated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_license_check', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_safe_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey')
    )
    # ### end Alembic commands ###
