"""add party default tax rate

Revision ID: c9409784e57f
Revises: 1c8ec1764fc1
Create Date: 2026-06-27 02:01:16.977587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9409784e57f'
down_revision: Union[str, None] = '1c8ec1764fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('default_tax_rate', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('default_tax_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'default_tax_rate')
    op.drop_column('customers', 'default_tax_rate')
    # ### end Alembic commands ###
